# Generated by Django 3.2 on 2022-03-19 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_collections_product_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='post',
            new_name='product',
        ),
    ]
