# Generated by Django 3.2 on 2022-03-30 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_post_review_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='approved',
        ),
    ]
