# Generated by Django 3.2 on 2022-03-30 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_review_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='approved',
        ),
    ]
